/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner{}

// V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner struct for V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner
type V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner struct {
	// The spoken text for this segment of the transcript.
	Speech string `json:"speech"`
	// The start time of this speech segment in seconds.
	StartTime float32 `json:"start_time"`
	// The end time of this speech segment in seconds.
	EndTime float32 `json:"end_time"`
	Speaker V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker `json:"speaker"`
}

type _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner(speech string, startTime float32, endTime float32, speaker V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner{}
	this.Speech = speech
	this.StartTime = startTime
	this.EndTime = endTime
	this.Speaker = speaker
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerWithDefaults() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner{}
	return &this
}

// GetSpeech returns the Speech field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetSpeech() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Speech
}

// GetSpeechOk returns a tuple with the Speech field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetSpeechOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speech, true
}

// SetSpeech sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) SetSpeech(v string) {
	o.Speech = v
}


// GetStartTime returns the StartTime field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetStartTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetStartTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) SetStartTime(v float32) {
	o.StartTime = v
}


// GetEndTime returns the EndTime field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetEndTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetEndTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) SetEndTime(v float32) {
	o.EndTime = v
}


// GetSpeaker returns the Speaker field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetSpeaker() V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker {
	if o == nil {
		var ret V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker
		return ret
	}

	return o.Speaker
}

// GetSpeakerOk returns a tuple with the Speaker field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) GetSpeakerOk() (*V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speaker, true
}

// SetSpeaker sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) SetSpeaker(v V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) {
	o.Speaker = v
}


func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["speech"] = o.Speech
	toSerialize["start_time"] = o.StartTime
	toSerialize["end_time"] = o.EndTime
	toSerialize["speaker"] = o.Speaker
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"speech",
		"start_time",
		"end_time",
		"speaker",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner := _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner(varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner struct {
	value *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) Get() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) Set(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner {
	return &NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


