/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner - struct for V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
type V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner struct {
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOfAsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOfAsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8: v,
	}
}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9: v,
	}
}

// V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11: v,
	}
}

// V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5: v,
	}
}

// V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner is a convenience function that returns V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 wrapped in V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
func V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9AsV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(v *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9) V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{
		V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9); err != nil {
				dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11); err != nil {
				dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5); err != nil {
				dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 = nil
	}

	// try to unmarshal data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9
	err = newStrictDecoder(data).Decode(&dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 = nil
		} else {
			if err = validator.Validate(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9); err != nil {
				dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 = nil
			} else {
				match++
			}
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 = nil
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 = nil
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) MarshalJSON() ([]byte, error) {
	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 != nil {
		return obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 != nil {
		return obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 != nil {
		return obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 != nil {
		return obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) GetActualInstanceValue() (interface{}) {
	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	}

	if obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 != nil {
		return *obj.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11 != nil {
		return *obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf11
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5 != nil {
		return *obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf5
	}

	if obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9 != nil {
		return *obj.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerOneOf9
	}

	// all schemas are nil
	return nil
}

type NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner struct {
	value *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) Get() *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) Set(val *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner(val *V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) *NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	return &NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


