/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker{}

// V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker struct for V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker
type V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker struct {
	// The name of the speaker.
	Name string `json:"name"`
	// The email address of the speaker.
	EmailAddress *string `json:"email_address,omitempty"`
}

type _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker(name string) *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker{}
	this.Name = name
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeakerWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeakerWithDefaults() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker{}
	return &this
}

// GetName returns the Name field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) SetName(v string) {
	o.Name = v
}


// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker := _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker(varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker struct {
	value *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) Get() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) Set(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker {
	return &NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInnerSpeaker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


