/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsPostRequest{}

// V2MeetingsMeetingIdCallRecordingsPostRequest struct for V2MeetingsMeetingIdCallRecordingsPostRequest
type V2MeetingsMeetingIdCallRecordingsPostRequest struct {
	// A publicly accessible URL to a video file of the call recording. Attio will download the video from this URL asynchronously.  **Requirements:** - **Protocol:** The URL must use the `https` protocol. - **File type:** The file must be a `.mp4` file. - **File size:** The file must not exceed 30MB in size. - **Accessibility:** For the request to be accepted, the URL must be publicly accessible. Attio will make a `HEAD` request to the URL to verify its accessibility and retrieve file metadata. The response to this request must include a `Content-Length` header.
	VideoUrl string `json:"video_url"`
}

type _V2MeetingsMeetingIdCallRecordingsPostRequest V2MeetingsMeetingIdCallRecordingsPostRequest

// NewV2MeetingsMeetingIdCallRecordingsPostRequest instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsPostRequest(videoUrl string) *V2MeetingsMeetingIdCallRecordingsPostRequest {
	this := V2MeetingsMeetingIdCallRecordingsPostRequest{}
	this.VideoUrl = videoUrl
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsPostRequestWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsPostRequestWithDefaults() *V2MeetingsMeetingIdCallRecordingsPostRequest {
	this := V2MeetingsMeetingIdCallRecordingsPostRequest{}
	return &this
}

// GetVideoUrl returns the VideoUrl field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequest) GetVideoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequest) GetVideoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VideoUrl, true
}

// SetVideoUrl sets field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequest) SetVideoUrl(v string) {
	o.VideoUrl = v
}


func (o V2MeetingsMeetingIdCallRecordingsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["video_url"] = o.VideoUrl
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"video_url",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdCallRecordingsPostRequest := _V2MeetingsMeetingIdCallRecordingsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsPostRequest)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsPostRequest(varV2MeetingsMeetingIdCallRecordingsPostRequest)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsPostRequest struct {
	value *V2MeetingsMeetingIdCallRecordingsPostRequest
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequest) Get() *V2MeetingsMeetingIdCallRecordingsPostRequest {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequest) Set(val *V2MeetingsMeetingIdCallRecordingsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsPostRequest(val *V2MeetingsMeetingIdCallRecordingsPostRequest) *NullableV2MeetingsMeetingIdCallRecordingsPostRequest {
	return &NullableV2MeetingsMeetingIdCallRecordingsPostRequest{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


