/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData{}

// V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData struct for V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData
type V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData struct {
	// Array of transcript segments with speech, timing, and speaker information. A maximum of 4000 transcript segments and 50 unique speakers are allowed per transcript.
	Transcript []V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner `json:"transcript"`
}

type _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData(transcript []V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData{}
	this.Transcript = transcript
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataWithDefaults() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData{}
	return &this
}

// GetTranscript returns the Transcript field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) GetTranscript() []V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner {
	if o == nil {
		var ret []V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner
		return ret
	}

	return o.Transcript
}

// GetTranscriptOk returns a tuple with the Transcript field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) GetTranscriptOk() ([]V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transcript, true
}

// SetTranscript sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) SetTranscript(v []V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestDataTranscriptInner) {
	o.Transcript = v
}


func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transcript"] = o.Transcript
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transcript",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData := _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData(varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData struct {
	value *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) Get() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) Set(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData {
	return &NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


