/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdGet200Response{}

// V2MeetingsMeetingIdGet200Response Success
type V2MeetingsMeetingIdGet200Response struct {
	Data Meeting `json:"data"`
}

type _V2MeetingsMeetingIdGet200Response V2MeetingsMeetingIdGet200Response

// NewV2MeetingsMeetingIdGet200Response instantiates a new V2MeetingsMeetingIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdGet200Response(data Meeting) *V2MeetingsMeetingIdGet200Response {
	this := V2MeetingsMeetingIdGet200Response{}
	this.Data = data
	return &this
}

// NewV2MeetingsMeetingIdGet200ResponseWithDefaults instantiates a new V2MeetingsMeetingIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdGet200ResponseWithDefaults() *V2MeetingsMeetingIdGet200Response {
	this := V2MeetingsMeetingIdGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *V2MeetingsMeetingIdGet200Response) GetData() Meeting {
	if o == nil {
		var ret Meeting
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdGet200Response) GetDataOk() (*Meeting, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V2MeetingsMeetingIdGet200Response) SetData(v Meeting) {
	o.Data = v
}


func (o V2MeetingsMeetingIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdGet200Response := _V2MeetingsMeetingIdGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdGet200Response)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdGet200Response(varV2MeetingsMeetingIdGet200Response)

	return err
}

type NullableV2MeetingsMeetingIdGet200Response struct {
	value *V2MeetingsMeetingIdGet200Response
	isSet bool
}

func (v NullableV2MeetingsMeetingIdGet200Response) Get() *V2MeetingsMeetingIdGet200Response {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdGet200Response) Set(val *V2MeetingsMeetingIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdGet200Response(val *V2MeetingsMeetingIdGet200Response) *NullableV2MeetingsMeetingIdGet200Response {
	return &NullableV2MeetingsMeetingIdGet200Response{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


