/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsObjectRecordsPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsPost200ResponseData{}

// V2ObjectsObjectRecordsPost200ResponseData struct for V2ObjectsObjectRecordsPost200ResponseData
type V2ObjectsObjectRecordsPost200ResponseData struct {
	Id V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId `json:"id"`
	// When this record was created.
	CreatedAt string `json:"created_at"`
	// A URL that links directly to the record page in the Attio web application.
	WebUrl string `json:"web_url"`
	// A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
	Values map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner `json:"values"`
}

type _V2ObjectsObjectRecordsPost200ResponseData V2ObjectsObjectRecordsPost200ResponseData

// NewV2ObjectsObjectRecordsPost200ResponseData instantiates a new V2ObjectsObjectRecordsPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsPost200ResponseData(id V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId, createdAt string, webUrl string, values map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) *V2ObjectsObjectRecordsPost200ResponseData {
	this := V2ObjectsObjectRecordsPost200ResponseData{}
	this.Id = id
	this.CreatedAt = createdAt
	this.WebUrl = webUrl
	this.Values = values
	return &this
}

// NewV2ObjectsObjectRecordsPost200ResponseDataWithDefaults instantiates a new V2ObjectsObjectRecordsPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsPost200ResponseDataWithDefaults() *V2ObjectsObjectRecordsPost200ResponseData {
	this := V2ObjectsObjectRecordsPost200ResponseData{}
	return &this
}

// GetId returns the Id field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetId() V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
	if o == nil {
		var ret V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetIdOk() (*V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) SetId(v V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) {
	o.Id = v
}


// GetCreatedAt returns the CreatedAt field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) SetCreatedAt(v string) {
	o.CreatedAt = v
}


// GetWebUrl returns the WebUrl field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetWebUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebUrl
}

// GetWebUrlOk returns a tuple with the WebUrl field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetWebUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebUrl, true
}

// SetWebUrl sets field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) SetWebUrl(v string) {
	o.WebUrl = v
}


// GetValues returns the Values field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetValues() map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner {
	if o == nil {
		var ret map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPost200ResponseData) GetValuesOk() (map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner, bool) {
	if o == nil {
		return map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner{}, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *V2ObjectsObjectRecordsPost200ResponseData) SetValues(v map[string][]V2ObjectsObjectRecordsPost200ResponseDataValuesValueInner) {
	o.Values = v
}


func (o V2ObjectsObjectRecordsPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["web_url"] = o.WebUrl
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"web_url",
		"values",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2ObjectsObjectRecordsPost200ResponseData := _V2ObjectsObjectRecordsPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsPost200ResponseData)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsPost200ResponseData(varV2ObjectsObjectRecordsPost200ResponseData)

	return err
}

type NullableV2ObjectsObjectRecordsPost200ResponseData struct {
	value *V2ObjectsObjectRecordsPost200ResponseData
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseData) Get() *V2ObjectsObjectRecordsPost200ResponseData {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseData) Set(val *V2ObjectsObjectRecordsPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPost200ResponseData(val *V2ObjectsObjectRecordsPost200ResponseData) *NullableV2ObjectsObjectRecordsPost200ResponseData {
	return &NullableV2ObjectsObjectRecordsPost200ResponseData{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


