/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest{}

// V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest struct for V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest
type V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest struct {
	Data V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData `json:"data"`
}

type _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest(data V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest{}
	this.Data = data
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestWithDefaults() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest{}
	return &this
}

// GetData returns the Data field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) GetData() V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData {
	if o == nil {
		var ret V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) GetDataOk() (*V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) SetData(v V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequestData) {
	o.Data = v
}


func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest := _V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest(varV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest struct {
	value *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) Get() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) Set(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest {
	return &NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdTranscriptPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


